export const CLEAR_CONTACTS = 'CLEAR_CONTACTS';

export const SET_PENDING_CONTACTS = 'SET_PENDING_CONTACTS';
export const ADD_PENDING_CONTACT = 'ADD_PENDING_CONTACT';
export const REMOVE_PENDING_CONTACT = 'REMOVE_PENDING_CONTACT';

export const SET_REQUESTS_CONTACTS = 'SET_REQUESTS_CONTACTS';
export const ADD_CONTACT_TO_REQUESTS = 'ADD_CONTACT_TO_REQUESTS';
export const REMOVE_CONTACT_FROM_REQUESTS = 'REMOVE_CONTACT_FROM_REQUESTS';

export const SET_FRIENDS = 'SET_FRIENDS';
export const ADD_FRIEND = 'ADD_FRIEND';
export const REMOVE_FRIEND = 'REMOVE_FRIEND';

export const REQUESTING_NEW_FRIEND = 'REQUESTING_NEW_FRIEND';
export const REQUESTING_NEW_FRIEND_SUCCESS = 'REQUESTING_NEW_FRIEND_SUCCESS';
export const REQUESTING_NEW_FRIEND_FAILURE = 'REQUESTING_NEW_FRIEND_FAILURE';
export const CONFIRMING_NEW_FRIEND = 'CONFIRMING_NEW_FRIEND';
export const CONFIRMING_NEW_FRIEND_SUCCESS = 'CONFIRMING_NEW_FRIEND_SUCCESS';
export const CONFIRMING_NEW_FRIEND_FAILURE = 'CONFIRMING_NEW_FRIEND_FAILURE'
